site_name: async-httpd-data-collector
site_url: https://ahttpdc-docs.codextechnologies.org/mkdocs
repo_url: https://github.com/straightchlorine/async-httpd-data-collector
repo_name: straightchlorine/async-httpd-data-collector

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.sections

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API Reference: api.md
  - Data Analysis:
    - Overview: analysis/index.md
    - Forecasting: analysis/prediction.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
